Caristocrate/Caristocrate.Main/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Caristocrate.Common.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Options;
using Caristocrate.Common;
using System.Web;
using System.Net.Http;
using System.IO;
using System.Net.Http.Headers;

namespace Caristocrate.Main.Controllers
{
    public class CustomerController : Controller
    {
        private AppSettings AppSetting { get; set; }
        public string AuthAccessToken { get; set; }
        public bool IsLogin { get; set; }
        public int UserNotificationFlag { get; set; }
        public string UserName { get; set; }
        public string UserImage { get; set; }
        public string UserEmail { get; set; }
        public string UserCountryCode { get; set; }
        public string UserPhoneNo { get; set; }
        private IHostingEnvironment _hostingEnvironment;

        public CustomerController(IOptions<AppSettings> settings, IHttpContextAccessor httpcontext, IHostingEnvironment environment)
        {            
            _hostingEnvironment = environment;
            AppSetting = settings.Value;

            try
            {
                UserName = "";
                UserImage = "";
                UserEmail = "";
                UserCountryCode = "";
                UserPhoneNo = "";

                if (httpcontext.HttpContext.Session.Keys.Count() > 0)
                {
                    if (httpcontext.HttpContext.Session.GetString("UserToken").ToString() != "")
                    {
                        AuthAccessToken = httpcontext.HttpContext.Session.GetString("UserToken").ToString();
                        UserName = httpcontext.HttpContext.Session.GetString("UserName").ToString();
                        UserImage = httpcontext.HttpContext.Session.GetString("UserImage").ToString();
                        UserEmail = httpcontext.HttpContext.Session.GetString("UserEmail").ToString();
                        UserCountryCode = httpcontext.HttpContext.Session.GetString("UserCountryCode").ToString();
                        UserPhoneNo = httpcontext.HttpContext.Session.GetString("UserPhone").ToString();
                        UserNotificationFlag = Convert.ToInt32(httpcontext.HttpContext.Session.GetString("UserNotificationFlag").ToString());
                        IsLogin = true;
                    }
                    else
                    {
                        AuthAccessToken = AppSetting.AccessToken;
                        IsLogin = false;
                    }
                }
                else
                {
                    AuthAccessToken = AppSetting.AccessToken;
                    IsLogin = false;
                }
            }
            catch (Exception ex)
            {
                AuthAccessToken = AppSetting.AccessToken;
                IsLogin = false;
            }
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Profile()
        {
            CustProfileModel.Response obj = new CustProfileModel.Response();
            try
            {
                if (IsLogin == false)
                {
                    return RedirectToAction("Index", "Home");
                }

                obj = GetCustomerProfile();

                int profilecompletionprogress = 0;
                try
                {
                    if (obj.data.name != null)
                    {
                        if (obj.data.name != "")
                        {
                            profilecompletionprogress = profilecompletionprogress + 10;
                        }
                    }
                    if (obj.data.email != null)
                    {
                        if (obj.data.email != "")
                        {
                            profilecompletionprogress = profilecompletionprogress + 10;
                        }
                    }
                    if (obj.data.details.country_code != null)
                    {
                        if (obj.data.details.country_code != "")
                        {
                            profilecompletionprogress = profilecompletionprogress + 10;
                        }
                    }
                    if (obj.data.details.phone != null)
                    {
                        if (obj.data.details.phone != "")
                        {
                            profilecompletionprogress = profilecompletionprogress + 10;
                        }
                    }
                   
                    if (obj.data.details.nationality != null)
                    {
                        if (obj.data.details.nationality != "")
                        {
                            profilecompletionprogress = profilecompletionprogress + 10;
                        }
                    }
                    if (obj.data.details.profession != null)
                    {
                        if (obj.data.details.profession != "")
                        {
                            profilecompletionprogress = profilecompletionprogress + 10;
                        }
                    }
                    if (obj.data.details.image != null)
                    {
                        if (obj.data.details.image != "")
                        {
                            profilecompletionprogress = profilecompletionprogress + 10;
                        }
                    }
                    if (obj.data.details.dob != null)
                    {
                        if (obj.data.details.dob != "")
                        {
                            profilecompletionprogress = profilecompletionprogress + 10;
                        }
                    }
                    if (obj.data.details.about != null)
                    {
                        if (obj.data.details.about != "")
                        {
                            profilecompletionprogress = profilecompletionprogress + 10;
                        }
                    }

                    if (obj.data.details.gender > 0)
                    { profilecompletionprogress = profilecompletionprogress + 10; }
                }
                catch (Exception ex)
                {

                    throw;
                }
                HttpContext.Session.SetString("UserProfileCompletion", profilecompletionprogress.ToString());
                HttpContext.Session.SetString("UserName", obj.data.name.ToString());                
                HttpContext.Session.SetString("UserImage", obj.data.details.image_url.ToString());
                HttpContext.Session.SetString("UserCountryCode", obj.data.details.country_code.ToString().Replace("+", ""));
                HttpContext.Session.SetString("UserPhone", obj.data.details.phone == null ? "" : obj.data.details.phone.ToString());
            }
            catch (Exception ex)
            {

            }

            return View(obj);
        }

        public IActionResult Notification()
        {
            CustNotificationModel.Response obj = new CustNotificationModel.Response();
            try
            {
                if (IsLogin == false)
                {
                    return RedirectToAction("Index", "Home");
                }

                obj = GetCustomerNotifications();
            }
            catch (Exception ex)
            {

            }

            return View(obj);
        }

        public IActionResult MyTradeIns(string data = "")
        {
            CustTradeInModel.Response obj = new CustTradeInModel.Response();
            int categoryID = 0;

            try
            {
                if (IsLogin == false)
                {
                    return RedirectToAction("Index", "Home");
                }
               
                if (data != "")
                {
                    string DecryptedQS = General.DecryptString(data, AppSetting.EncryptionKey);
                    var QSParams = HttpUtility.ParseQueryString(DecryptedQS);
                    categoryID = QSParams.Get("categoryID") != null ? Convert.ToInt32(QSParams.Get("categoryID")) : 0;
                }

                obj = GetCustomerTradeIn(0, 10);
            }
            catch (Exception ex)
            {

            }

            ViewData["categoryID"] = categoryID;

            return View(obj);
        }

        public IActionResult MyEvaluations()
        {
            CustTradeInModel.Response obj = new CustTradeInModel.Response();
            try
            {
                if (IsLogin == false)
                {
                    return RedirectToAction("Index", "Home");
                }

                obj = GetCustomerTradeIn(0, 20);
            }
            catch (Exception ex)
            {

            }

            return View(obj);
        }

        public IActionResult MyEvaluationbyID(int id)
        {
            CustTradeInByIDModel.Response obj = new CustTradeInByIDModel.Response();
            try
            {
                if (IsLogin == false)
                {
                    return RedirectToAction("Index", "Home");
                }

                obj = GetCustomerTradeInbyID(id, 0);
            }
            catch (Exception ex)
            {

            }

            return View(obj);
        }

        public IActionResult MyTradeInsbyID(int id)
        {
            CustTradeInByIDModel.Response obj = new CustTradeInByIDModel.Response();
            try
            {
                if (IsLogin == false)
                {
                    return RedirectToAction("Index", "Home");
                }

                obj = GetCustomerTradeInbyID(id, 0);
            }
            catch (Exception ex)
            {

Caristocrate/Caristocrate.Main/Views/Shared/Components/FooterMenu/FooterMenuViewComponent.cs
using Caristocrate.Common;
using Caristocrate.Common.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Options;

namespace Caristocrate.Main.Views.Shared.Components.FooterMenu
{
    public class FooterMenuViewComponent : ViewComponent
    {
        private AppSettings AppSetting { get; set; }
        public string AuthAccessToken { get; set; }

        public FooterMenuViewComponent(IOptions<AppSettings> settings, IHttpContextAccessor httpcontext)
        {
            AppSetting = settings.Value;
            try
            {
                if (httpcontext.HttpContext.Session.Keys.Count() > 0)
                {
                    if (httpcontext.HttpContext.Session.GetString("UserToken").ToString() != "")
                    {
                        AuthAccessToken = httpcontext.HttpContext.Session.GetString("UserToken").ToString();
                    }
                    else
                    {
                        AuthAccessToken = AppSetting.AccessToken;
                    }
                }
                else
                {
                    AuthAccessToken = AppSetting.AccessToken;
                }
            }
            catch (Exception ex)
            {
                AuthAccessToken = AppSetting.AccessToken;
            }
        }

        public async Task<IViewComponentResult> InvokeAsync(CategoryModel.Response categories)
        {

            //CategoryModel.Response Categories = new CategoryModel.Response();
            try
            {
                if (categories == null)
                {
                    categories = GetBaseCategories();
                }
            }
            catch (Exception ex)
            { }
            return View(categories);
        }

        public CategoryModel.Response GetBaseCategories()
        {
            CategoryModel.Response obj = new CategoryModel.Response();
            try
            {
                string CategoryAPIURL = AppSetting.BaseURL + AppSetting.CategoryAPI;
                string APIResponse = "";
                APIWebRequest objAPI = new APIWebRequest(CategoryAPIURL, "GET", "", AuthAccessToken, 1);
                APIResponse = objAPI.GetResponse();
                obj = Newtonsoft.Json.JsonConvert.DeserializeObject<CategoryModel.Response>(APIResponse);
            }
            catch (Exception ex)
            { }
            return obj;
        }
    }
}

Caristocrate/Caristocrate.Main/Views/Shared/Components/HeaderMenu/HeaderMenuViewComponent.cs
using Caristocrate.Common;
using Caristocrate.Common.Models;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Session;
using System.Runtime.Serialization.Json;

namespace Caristocrate.Main.Views.Shared.Components.HeaderMenu
{
    public class HeaderMenuViewComponent : ViewComponent
    {
        private AppSettings AppSetting { get; set; }
        public string AuthAccessToken { get; set; }

        public HeaderMenuViewComponent(IOptions<AppSettings> settings, IHttpContextAccessor httpcontext)
        {            
            AppSetting = settings.Value;
            try
            {
                if (httpcontext.HttpContext.Session.Keys.Count() > 0)
                {
                    if (httpcontext.HttpContext.Session.GetString("UserToken").ToString() != "")
                    {
                        AuthAccessToken = httpcontext.HttpContext.Session.GetString("UserToken").ToString();
                    }
                    else
                    {
                        AuthAccessToken = AppSetting.AccessToken;
                    }
                }
                else
                {
                    AuthAccessToken = AppSetting.AccessToken;
                }
            }
            catch (Exception ex)
            {
                AuthAccessToken = AppSetting.AccessToken;
            }
        }

        public async Task<IViewComponentResult> InvokeAsync(CategoryModel.Response Categories)
        {

            //CategoryModel.Response Categories = new CategoryModel.Response();
            try
            {
                if (Categories == null)
                {
                    Categories = GetBaseCategories();
                }
            }
            catch (Exception ex)
            { }
            return View(Categories);
        }

        public CategoryModel.Response GetBaseCategories()
        {
            CategoryModel.Response obj = new CategoryModel.Response();
            try
            {
                string CategoryAPIURL = AppSetting.BaseURL + AppSetting.CategoryAPI;
                string APIResponse = "";
                APIWebRequest objAPI = new APIWebRequest(CategoryAPIURL, "GET", "", AuthAccessToken, 1);
                APIResponse = objAPI.GetResponse();
                obj = Newtonsoft.Json.JsonConvert.DeserializeObject<CategoryModel.Response>(APIResponse);
            }
            catch (Exception ex)
            { }
            return obj;
        }
    }
}

Caristocrate/Caristocrate.Main/Views/Shared/_Header.cshtml
@using Caristocrate.Common.Models
@using Caristocrate.Common
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpcontext
@{
    Layout = null;
    string encryptionKey = "E546C8DF278CD5931069B522E695D4F2";
    CategoryModel.Response categories = ViewData["Maincategories"] as CategoryModel.Response;
}

<style type="text/css">
    /*#headermenu1 a {
        text-transform: lowercase;
    }

        #headermenu1 a::first-letter {
            text-transform: uppercase;
        }

    #headermenu2 a {
        text-transform: lowercase;
    }

        #headermenu2 a::first-letter {
            text-transform: uppercase;
        }*/


    .badge {
        position: absolute;
        top: -10px;
        right: -10px;
        padding: 5px 10px;
        border-radius: 50%;
        background: red;
        color: white;
    }
</style>


<header class="header">
    <div class="topBar">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <a href="javascript:;"><i class="fa fa-phone" aria-hidden="true"></i>  &nbsp; +44 36 3456 5976</a>
                    <a href="javascript:;" class="border0"><i class="fa fa-envelope" aria-hidden="true"></i> &nbsp; info@caristocrat.com </a>
                </div>
                <div class="col-md-6">
                    <div class="socialBox">
                        <a href="javascript:;"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                        <a href="javascript:;"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                        <a href="javascript:;"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
                        <a href="javascript:;"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                        <a href="javascript:;"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="logoBar">
        <div class="container">
            <div class="row justify-content-end">
                @*<div class="col-md-4 hidesmall"></div>*@
                <div class="col-lg-4 col-md-6">
                    <a href="/" class="logo"><img src='@Url.Content("~/assets/images/logo-new.svg")' alt="" class="img-responsive"></a>
                </div>
                <div class="col-lg-5 col-md-6 my-auto">
                    <div class="topRight clearfix">
                        <div class="searchBar">
                            <div class="field">
                                <input type="text" name="" class="txtMainSearch" placeholder="Search...">
                                <button onclick="HideSearch(this)" type="submit">&times;</button>
                            </div>
                        </div>
                        <div class="searchBox">
                            <span onclick="ShowSearch(this)" class="icon-search"></span>
                        </div>

                        <div class="langBox">
                            <img src='@Url.Content("~/assets/images/lang-icon.png")' alt="">
                            <i class="menuarrow fa-angle-down fa"></i>
                            <div class="language-dropdown d-none" id="ddllanguage1">
                                
                            </div>
                        </div>

                        @*<div class="langBox" style="display:none">
                            <img src='@Url.Content("~/assets/images/lang-icon.png")' alt="">
                            <select>
                                <option value="">UAE</option>
                                <option value="">Eng</option>
                            </select>
                        </div>*@
                        <div class="loginBox">
                            @if (Context.Session.Keys.Count() > 0)
                            {

                                @*<ul>
                    <li><a href="@Url.Action("Profile", "Customer")">My Account</a></li>
                </ul>*@
                                <div class="user_wid">
                                    <h3>@httpcontext.HttpContext.Session.GetString("UserName").ToString() <span>Your Profile is @httpcontext.HttpContext.Session.GetString("UserProfileCompletion").ToString()% Completed</span></h3>
                                    <a href="@Url.Action("Profile", "Customer")">
                                        @if (httpcontext.HttpContext.Session.GetString("UserProfileCompletion").ToString() == "100")
                                        {
                                            <figure style="border:3px solid green"><img src="@httpcontext.HttpContext.Session.GetString("UserImage").ToString()" alt=""></figure>
                                        }
                                        else
                                        {
                                            <figure><img src="@httpcontext.HttpContext.Session.GetString("UserImage").ToString()" alt=""><span></span></figure>
                                        }
                                    </a>
                                    <a href="@Url.Action("Notification", "Customer")" class="notificationBtn"><span class="icon-notification"></span><span class="badge" style="display:none"></span></a>
                                </div>
                            }
                            else
                            {
                                <ul>
                                    <li><a href="javascript:;" data-toggle="modal" data-target="#exampleModalCenter" class="btnShowLogin">Login</a></li>
                                    <li><a href="@Url.Action("Register", "Account")">Signup</a></li>
                                </ul>
                            }
                        </div>
                        @*<a style="display:none;" href="javascript:;" data-toggle="modal" data-target="#exampleModalCenter" class="hdnbtnShowLogin"></a>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
    <i class="fa fa-bars" aria-hidden="true menuBtn"></i>
    <div class="mainNav">
        <a href="javascript:void(0)" class="closebtn">×</a>
        <div class="container" id="headermenu1">
            @await Component.InvokeAsync("HeaderMenu")
        </div>
    </div>

    <div class="sticky_header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-1 col-md-1 stickylogo">
                    <a href="/" class="logo"><img src="@Url.Content("~/assets/images/logo-new.svg")" alt="" class="img-responsive"></a>
                </div>
               <!-- <div class="col-lg-7 col-md-7"> -->
                    <div class="col-lg-8 col-md-8">
                        <div class="stikyNav" id="headermenu2">
                            @await Component.InvokeAsync("HeaderMenu")
                        </div>
                    </div>
                <!--<div class="col-lg-4 col-md-4 topRight ">--> 
                <div class="col-lg-3 col-md-3 topRight ">
                    <div class="searchBar2">
                        <div class="field">
                            <input type="text" name="" class="txtMainSearch2" placeholder="Search...">
                            <button onclick="HideSearch2(this)" type="submit">&times;</button>
                        </div>
                    </div>
                    <div class="searchBox2">
                        <span onclick="ShowSearch2(this)" class="icon-search"></span>
                    </div>
                    @*<div style="display:none;" class="langBox">
                <img src='@Url.Content("~/assets/images/lang-icon.png")' alt="">
                <select>
                    <option value="">UAE</option>
                    <option value="">Eng</option>
                </select>
            </div>*@
                    <div class="langBox">
                        <img src='@Url.Content("~/assets/images/lang-icon.png")' alt="">
                        <i class="menuarrow fa-angle-down fa"></i>
                        <div class="language-dropdown d-none" id="ddllanguage2">

                        </div>
                    </div>
                    @if (Context.Session.Keys.Count() > 0)
                    {
                        <ul class="user_wid">
                            <li>
                                <h3>@httpcontext.HttpContext.Session.GetString("UserName").ToString() <span>Your Profile is @httpcontext.HttpContext.Session.GetString("UserProfileCompletion").ToString()% Completed</span></h3>
                            </li>
                            <li>
                                <a href="@Url.Action("Profile", "Customer")">
                                    @if (httpcontext.HttpContext.Session.GetString("UserProfileCompletion").ToString() == "100")
                                    {
                                        <figure style="border:3px solid green"><img src="@httpcontext.HttpContext.Session.GetString("UserImage").ToString()" alt=""></figure>
                                    }
                                    else
                                    {
                                        <figure><img src="@httpcontext.HttpContext.Session.GetString("UserImage").ToString()" alt=""><span></span></figure>
                                    }
                                </a>
                            </li>
                            <li><a href="@Url.Action("Notification", "Customer")" class="notificationBtn"><span class="icon-notification"></span><span class="badge" style="display:none"></span></a></li>
                        </ul>
                    }
                    else
                    {
                        <ul>
                            <li><a href="javascript:;" data-toggle="modal" data-target="#exampleModalCenter" class="btnShowLogin">Login</a> | </li>
                            <li><a href="@Url.Action("Register", "Account")">Signup</a></li>
                        </ul>
                    }
                    @*<ul>

                <li><a href="#">Login</a> | </li>
                <li><a href="#">Sign up</a></li>
            </ul>*@
                </div>
            </div>
        </div>
    </div>

</header><!-- /header -->

<script type="text/javascript">


    $(window).bind("load", function () {
        setTimeout(function () {
            GetCustNotificationCount();
        }, 2000);
    });

    $(document).ready(function () {
        //GetHeaderMenu();
        $('#headermenu1').find("a").each(function () {
            $(this).text(titleCase($(this).text()));
        });
        $('#headermenu2').find("a").each(function () {
            $(this).text(titleCase($(this).text()));
        });
    })

    function GetCustNotificationCount() {
        $(".badge").hide();
        $.ajax({
            dataType: "text",
            async: true,
            type: 'GET',
            url: '@Url.Action("GetCustomerNotificationCount", "Home")',
            success: function (data) {
                if (data > 0) {
                    $(".badge").text(data);
                    $(".badge").show();
                }
            }, complete: function () { 

                
            }
        });
    }

    function GetHeaderMenu() {   
        $('#headermenu1').html('');
        $('#headermenu2').html('');
        $.ajax({
            dataType: "html",
            async: true,
            type: 'GET',
            url: '@Url.Action("HeaderMenu", "Home")',
            type: 'GET',
            success: function (data) {
                $('#headermenu1').html(data);
                $('#headermenu2').html(data);
            }, complete: function () { 

                $('#headermenu1').find("a").each(function () {
                    $(this).text(titleCase($(this).text()));
                });
                $('#headermenu2').find("a").each(function () {
                    $(this).text(titleCase($(this).text()));
                });
            }
        });
    }

    

    @*function GetHeaderRegion() {   
        $('#ddllanguage1').html('');
        $('#ddllanguage2').html('');
        $.ajax({
            dataType: "html",
            async: true,
            type: 'GET',
            url: '@Url.Action("HeaderRegions", "Home")',
            type: 'GET',
            success: function (data) {
                $('#ddllanguage1').html(data);
                $('#ddllanguage2').html(data);
            }, complete: function () { 
                //$('.language-dropdown .round').on('click', function () {
                //    //$('.chk .active-check').toggleClass('active-check');
                //    $(this).toggleClass('active-check');
                //});

                $(".menuarrow").click(function () {
                    $(".language-dropdown").toggleClass('d-none');
                });

                $(".menuarrow").click(function () {
                    $(this).parent("li").children(".subMenu").toggle();
                    $(this).toggleClass("fa fa-angle-down fa fa-angle-up");
                });
                
            }
        });
    }*@
</script>

Caristocrate/Caristocrate.Main/Views/Shared/_ProfileLayout.cshtml
@using Caristocrate.Common
@using Microsoft.AspNetCore.Http
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    //string encryptionKey = "E546C8DF278CD5931069B522E695D4F2";
}

<div class="profile_nav">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <ul>
                    <li><a href="@Url.Action("MyAccount", "Customer")">My Account</a></li>
                    @*<li class="dropMenu">
                        <a href="@Url.Action("MyTradeIns", "Customer")">My Trade Ins</a>
                        <div class="subMenu">
                            <ul>
                                <li><a href="@Url.Action("MyTradeIns", "Customer", new { data= General.EncryptString("categoryID=28", encryptionKey) })">Luxury New Cars</a></li>
                                <li><a href="@Url.Action("MyTradeIns", "Customer", new { data= General.EncryptString("categoryID=25", encryptionKey) })">The Outlet Mall</a></li>
                                <li><a href="@Url.Action("MyTradeIns", "Customer", new { data= General.EncryptString("categoryID=26", encryptionKey) })">Approved Pre-Owned</a></li>
                                <li><a href="@Url.Action("MyTradeIns", "Customer", new { data= General.EncryptString("categoryID=27", encryptionKey) })">Classic Cars</a></li>
                            </ul>
                        </div>
                    </li>*@
                    @*<li><a href="javascript:;">Reviews Posted</a></li>*@
                    <li><a href="@Url.Action("MyTradeIns", "Customer")">My Trade Ins</a></li>
                    <li><a href="@Url.Action("MyEvaluations", "Customer")">My Evaluations</a></li>
                </ul>
            </div>
            <div class="col-md-4 text-right">
                <ul>
                    @*<li><a href="@Url.Action("Notification", "Customer")"><span class="icon-notification"></span> Notifications</a></li>*@
                    <li><a href="@Url.Action("Setting", "Customer")"><span class="icon-make"></span> Settings</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

@RenderBody()